# Generated by Django 3.1.7 on 2021-04-11 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_projects', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='owner_of_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.JSONField(blank=True, default=dict, null=True)),
                ('name', models.CharField(max_length=30)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('home_markdown', models.TextField(blank=True, default=None, null=True)),
                ('home_html', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ProjectControl.project')),
            ],
        ),
        migrations.CreateModel(
            name='Dependence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.JSONField(blank=True, default=dict, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dependencies', to='ProjectControl.version')),
                ('project_dependency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_dependence', to='ProjectControl.version')),
            ],
        ),
    ]
