# Generated by Django 3.1.7 on 2021-02-25 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home_markdown', models.TextField(blank=True, default=None, null=True)),
                ('home_html', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(default='0.1.0', max_length=30)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_projects', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(related_name='owner_of_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.JSONField(blank=True, default=None, null=True)),
                ('version', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ProjectControl.project')),
            ],
        ),
        migrations.CreateModel(
            name='Dependence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProjectControl.filedirectory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dependencies', to='ProjectControl.project')),
                ('project_dependency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_dependence', to='ProjectControl.project')),
            ],
        ),
    ]
