# Generated by Django 3.1.7 on 2021-04-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectControl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependence',
            name='project_dependency_version',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_dependence', to='ProjectControl.version'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dependence',
            name='project_versions',
            field=models.ManyToManyField(related_name='dependencies', to='ProjectControl.Version'),
        ),
        migrations.AlterField(
            model_name='dependence',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dependencies', to='ProjectControl.project'),
        ),
        migrations.AlterField(
            model_name='dependence',
            name='project_dependency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='as_dependence', to='ProjectControl.project'),
        ),
    ]
