# Generated by Django 3.1.7 on 2021-04-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectControl', '0002_auto_20210412_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependence',
            name='project_versions',
            field=models.ManyToManyField(blank=True, related_name='dependencies', to='ProjectControl.Version'),
        ),
    ]
