# Generated by Django 3.1.7 on 2021-04-11 20:29

import ThemesControl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProjectControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('background', models.ImageField(blank=True, null=True, upload_to=ThemesControl.models.upload_back)),
                ('background_small', models.ImageField(default='static\\images\\no-image.png', upload_to=ThemesControl.models.upload_small)),
                ('projects', models.ManyToManyField(blank=True, related_name='theme', to='ProjectControl.Project')),
            ],
        ),
    ]
