# Generated by Django 3.1.6 on 2021-02-21 19:19

import ThemesControl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontSite', '0001_initial'),
        ('ThemesControl', '0002_auto_20210221_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='background',
            field=models.ImageField(null=True, upload_to=ThemesControl.models.upload_back),
        ),
        migrations.AddField(
            model_name='theme',
            name='background_small',
            field=models.ImageField(default='images/no-image.png', upload_to=ThemesControl.models.upload_small),
        ),
        migrations.AlterField(
            model_name='theme',
            name='projects',
            field=models.ManyToManyField(related_name='theme', to='FrontSite.Projects'),
        ),
    ]
